CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'articles'

urlpatterns = [
  path('', views.index, name = 'index'),
  path('<int:pk>/', views.detail, name = 'detail'),

  # path('new/', views.new, name = 'new'),
  path('create/', views.create, name = 'create'),

  path('<int:pk>/delete/', views.delete, name = 'delete'),

  # path('<int:pk>/edit/', views.edit, name = 'edit'),
  path('<int:pk>/update/', views.update, name = 'update'),
  
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
  title = models.CharField(max_length = 20)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add = True)
  updated_at = models.DateTimeField(auto_now = True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
  class Meta:
    model = Article 
    fields = '__all__'
    widgets = {
    'title': forms.TextInput(attrs={
      'class': 'form-control',
      'style': 'width:500px;',
      'placeholder': '글 제목을 입력하세요'
      }),
    'content': forms.Textarea(attrs={
      'class': 'form-control',
      'style': 'width:500px;',
      'placeholder': '글 내용을 입력하세요'
      }),
    }

articles/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .models import Article

from .forms import ArticleForm

def index(request): # 전체 게시글 조회
  articles = Article.objects.all()
  context = {
    'articles' : articles,
  }
  return render(request, 'articles/index.html', context)

def detail(request, pk): #단일 게시글 조회
  article = Article.objects.get(pk = pk)
  context = {
    'article' : article,
  }
  return render(request, 'articles/detail.html', context)

# def new(request):
#   return render(request, 'articles/new.html')

# def create(request):
#   # 데이터를 POST요청을 통해 서버로 전송 - 보안상 안전하기 때문에
#   title = request.POST.get('title')
#   content = request.POST.get('content')

#   # 코드의 간결성 : 객체를 생성하면서 동시에 속성을 설정
#   article = Article(title = title, content = content)
#   # 테이터 관리의 원칙 : 안정성 ---> 유효성 검사!!
#   article.save()

#   return redirect('articles:detail', article.pk)
#   # 데이터 변경 되었을 때 경로에 요청

# 1. 사용자가 폼 페이지를 처음 방문(GET요청), 비어있는 폼을 랜더링 사용자가 데이터를 입력할 수 있게
# 2. 폼을 제출하면(POST요청), 제출된 데이터로 인스턴스 생성
# 3. 유효성 검사 후, 유효하면 DB에 저장, 사용자를 상세 페이지로 리다이렉트
# 1-1. 제출버튼을 누르지 않은 경우(POST요청이 아닌경우) 모든 필드가 비어 있는 상태로 사용자에게 보여지게

def create(request):
  if request.method == 'POST':
    form = ArticleForm(request.POST)
    # 1. 모든 필수 필드가 채워져 있다.
    # 2. 입력된 데이터가 필드의 조건(ex 데이터 형식)을 만족해야 한다.
    if form.is_valid():
      article = form.save()
      return redirect('articles:detail', article.pk)
  else:
    form = ArticleForm()
    
  context = {
    'form' : form,
  }
  return render(request, 'articles/create.html', context)

def update(request, pk):
  article = Article.objects.get(pk = pk)

  if request.method == 'POST':
    form = ArticleForm(request.POST, instance=article)
    if form.is_valid():
      form.save()
      return redirect('articles:detail', article.pk)
  else:
    # 기존 데이터를 form instace에 넣어준다.
    form = ArticleForm(instance=article)

  context = {
    'article' : article,
    'form' : form,
  }

  return render(request, 'articles/update.html', context)


def delete(request, pk):
  article = Article.objects.get(pk = pk)
  article.delete()

  return redirect('articles:index')

# def edit(request, pk):
#   article = Article.objects.get(pk = pk)
#   context = {
#     'article' : article,
#   }
#   return render(request, 'articles/edit.html', context)

# def update(request, pk):
#   article = Article.objects.get(pk = pk)

#   article.title = request.POST.get('title')
#   article.content = request.POST.get('content')

#   article.save()

#   return redirect('articles:detail', article.pk)

articles/templates/articles/create.html
{% extends "base.html" %}
{% block content %}

  <h2 class="tdl"> CREATE </h2>

  <form action="{% url "articles:create" %}" method = "POST">
    {% csrf_token %}
    {{ form.as_p }}

    <hr>

    <a type="button" class="btn btn-danger" href="{%url "articles:index" %}">Cancel</a>
    <button type="submit" class="btn btn-success">Create</button>
    
  </form>
  <hr>

{% endblock content %}

articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}

  <h2> DETAIL </h2>

  <table class="table">
    <thead>
      <tr class="table-secondary">
        <th scope="col">글 제목<span style="display:inline-block; width:150px;"></span></th>
        <th scope="col">글 내용<span style="display:inline-block; width:300px;"></th>
        <th scope="col">작성 시각<span style="display:inline-block; width:200px;"></th>
        <th scope="col">수정 시각<span style="display:inline-block; width:200px;"></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <tr>
        <td>{{article.title}}</td>     
        <td>{{article.content}}</td>
        <td>{{article.created_at}}</td>
        <td>{{article.updated_at}}</td>  
      </tr>
    </tbody>
  </table>

 
  <a type="button" class="btn btn-warning" href="{%url "articles:update" article.pk%}">Update</a>
  <a type="button" class="btn btn-danger" href="{%url 'articles:delete' article.pk%}">Delete</a>
  <a type="button" class="btn btn-success" href="{%url 'articles:index'%}">Home</a>

{% endblock content %}

articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}

  <h3 class="tdl">To Do list</h3>

  <table class="table">
    <thead>
      <tr class="table-secondary">
        <th scope="col">글 번호<span style="display:inline-block; width:20px;"></span></th>
        <th scope="col">글 제목<span style="display:inline-block; width:150px;"></span></th>
        <th scope="col">글 내용<span style="display:inline-block; width:300px;"></span></th>
        <th scope="col">Action<span style="display:inline-block; width:200px;"></span></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for article in  articles%}
        <tr>
            <td>{{forloop.counter}}</td>
            
              <td><a href="{% url "articles:detail" article.pk %}">{{article.title|slice:":10"}}</a></td>
            
            <td>{{article.content|slice:":10"}}</td>
            <td>
              <a type="button" class="btn btn-outline-warning" href="{%url 'articles:update' article.pk%}">Update</a>
              <a type="button" class="btn btn-outline-danger" href="{%url 'articles:delete' article.pk%}">Delete</a>
            </td>  
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a type="button" class="btn btn-outline-success" href="{%url 'articles:create' %}">Create</a>



{% endblock content %}

articles/templates/articles/update.html
{% extends "base.html" %}


{% block content %}

  <h2> UPDATE </h1>

  <form action="{% url "articles:update" article.pk %}" method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <hr>
    <a type="button" class="btn btn-danger" href="{%url "articles:index" %}">Cancel</a>
    <button type="submit" class="btn btn-success">Update</button>
  </form>
  <hr>


{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      .card-wrapper {
        margin: 10px;
        padding : 20px;
        border-radius: 10px;
        border: 1px solid darkgray;
        display: inline-block;
      }
    </style>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/style.css" />
  </head>
  <body>
    <div class="card-wrapper test">
       {% block content %}
       {% endblock content %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>